name: Deploy Cinema-Api to Azure

on:
  push:
    branches:
      - release
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: cinema-api

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    - name: Restore dependencies
      run: dotnet restore ./backend/CinemaApi/CinemaApi.sln

    - name: Build the solution
      run: dotnet build ./backend/CinemaApi/CinemaApi.sln --configuration Release --no-restore

    - name: Publish the app
      run: dotnet publish ./backend/CinemaApi/CinemaWebApi/CinemaWebApi.csproj --configuration Release --no-build -o ./publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: production
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_CINEMA_API }}
        package: ./publish
